Milestone 4 logic
peterrobert/React-calculator pull request #4
Opened 2021-01-14 19:04 UTC by peterrobert

In this milestone, I created the following:

1. Calculate.js  file for the logic.
2. Operate.js file for the logic.

2021-01-14 20:46 UTC, mosaaleb requested changes
#### Changes required

Well done @peterrobert :clap:. You have already implemented most of the requirements from this milestone. However, there are some console error and other requirements we need to handle before moving on. Kindly take a look at my comments below:

- [x] `node_modules` is currently tracked by git. Kindly make sure to properly add node_modules in .gitignore. Hint: remove the `\`. Read more about [gitignore rules](https://git-scm.com/docs/gitignore)

- [x] Let's import `calculate.js` in `App` component. 

Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2021-01-14 20:46 UTC, mosaaleb commented on src/components/Button.js
> +  color: PropTypes.string.isRequired,
- [ ] I got a console error here:
![Screenshot from 2021-01-14 22-15-38](https://user-images.githubusercontent.com/4246637/104644192-1f0e4e80-56b6-11eb-9d46-3ea5a22da928.png)

Make sure to pass the color prop or declare a default prop [declaring default props](![Screenshot from 2021-01-14 22-15-38](https://user-images.githubusercontent.com/4246637/104644192-1f0e4e80-56b6-11eb-9d46-3ea5a22da928.png))

2021-01-14 20:46 UTC, mosaaleb commented on src/components/Button.js
> +export const Button = props => {
- [ ] **[OPTIONAL]** We can directly de-structure objects inside function arguments, which will save use a few lines.

```js
export const Button = ({ name, color, wide}) => {
```

2021-01-14 20:46 UTC, mosaaleb commented on src/components/Button.js
> +  wide: PropTypes.string.isRequired,
- [ ] I got also another console error here:
![Screenshot from 2021-01-14 22-23-47](https://user-images.githubusercontent.com/4246637/104645058-3d287e80-56b7-11eb-9c8a-7d3b912afd28.png)

Let's fix this.

2021-01-14 20:46 UTC, mosaaleb commented on src/logic/operate.js
> +  if (operation === '=') {
- [ ] We need to replace this condition with `%` which turns a number to precentage notation.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png)

2021-01-14 20:46 UTC, mosaaleb commented on src/logic/calculate.js
> +  if (button === '+/-') {
- [ ] Good job done here, but we need to handle more cases to cover all the possible scenarios.
Here are some cases to consider to structure the calculator object `total, next, operation`:
- what if the button is a number?
- what if the button is a number and the previous click is an operation?
- what if the button is '.'

Kindly make sure to cover all the possible scenarios.

2021-01-14 20:46 UTC, mosaaleb commented on .eslintrc.json
> +        "import/prefer-default-export": "off",
- [ ] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png)

2021-01-21 16:30 UTC, bellom requested changes
## Hi @peterrobert  :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

**You seems to introduce a bug, `npm start` not working**
For some reason,  you pushed the `node_modules` folder to GitHub, you could ignore this in the `gitignore` file, perhaps that would help.

Try to delete the `node_modules`, add it to the `gitignore` and run `npm i`

Screenshot from your app;
![image](https://user-images.githubusercontent.com/31897434/105380945-bd4a6900-5c0e-11eb-8467-076a9bd3f592.png)


![image](https://user-images.githubusercontent.com/31897434/78641536-4b847700-78a9-11ea-874a-c5f582e0f7c2.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-01-21 16:30 UTC, bellom commented on src/logic/operate.js
> +      data = num1.times(Big(0.01));
When it comes to `%` we only need one operand.
example: click `10` then `%` = 0.01
This should work.
Example: `num1 = (num1 *= 0.01).toString();`

You might want to add `toString()` at the end of your cases.

2021-01-25 07:37 UTC, mikenath223 requested changes
### Hi @peterrobert 👋

**You've done quite well here fixing most issues raised in the previous review.👌**

 However to move forward let's fix this:

- [ ]  Delete node_modules from the development branch. To do this switch to the development branch then run `rm -rf node_modules` in your terminal then next push directly to the development branch. It's important that node_modules is removed from the development branch. Kindly fix this.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2021-01-25 07:56 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2021-01-25 08:14 UTC, merged